version: '3'

services:
  malcopolo-db:
    container_name: malcopolo-db
    image: mysql:8.0
    restart: always
    ports:
      - ${MYSQL_PORT}:3306
    env_file:
      - .env
    volumes:
      - ~/malcopolo-db:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

  malcopolo-testdb:
    container_name: malcopolo-testdb
    image: mysql:8.0
    restart: always
    ports:
      - 3331:3306
    env_file:
      - .env.test
    volumes:
      - ~/malcopolo-testdb:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
